---
- name: Test connection to vm3
  hosts: vm3 # This will specifically target the host named 'vm3' in your inventory
  gather_facts: false # No need to gather facts for a simple ping, speeds up execution

  tasks:
    - name: Ping the host
      ansible.builtin.ping:
